// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu_YG_dR3TVWD3uhawpUjVhXHK9MTc01k',
    appId: '1:281299819563:web:35af9441f324c1ea69de6e',
    messagingSenderId: '281299819563',
    projectId: 'all-in-one-students-app',
    authDomain: 'all-in-one-students-app.firebaseapp.com',
    storageBucket: 'all-in-one-students-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuvFQMB4TC0DHYrjA8QYjDgU-HaNsi7I',
    appId: '1:281299819563:android:fe22a957f9558b6869de6e',
    messagingSenderId: '281299819563',
    projectId: 'all-in-one-students-app',
    storageBucket: 'all-in-one-students-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv21sIrev8MwHo9KTTrWzocynRbCAWc3k',
    appId: '1:281299819563:ios:5203de1cb832e43b69de6e',
    messagingSenderId: '281299819563',
    projectId: 'all-in-one-students-app',
    storageBucket: 'all-in-one-students-app.appspot.com',
    iosBundleId: 'com.example.forStudents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv21sIrev8MwHo9KTTrWzocynRbCAWc3k',
    appId: '1:281299819563:ios:b03ac93597b2d1ed69de6e',
    messagingSenderId: '281299819563',
    projectId: 'all-in-one-students-app',
    storageBucket: 'all-in-one-students-app.appspot.com',
    iosBundleId: 'com.example.forStudents.RunnerTests',
  );
}
